package com.heitian.ssm.model;

public class User {
    public String getUse_Id() {
        return use_Id;
    }

    public void setUse_Id(String use_Id) {
        this.use_Id = use_Id;
    }

    public String getUser_Password() {
        return user_Password;
    }

    public void setUser_Password(String user_Password) {
        this.user_Password = user_Password;
    }

    public String getUser_Auth() {
        return user_Auth;
    }

    public void setUser_Auth(String user_Auth) {
        this.user_Auth = user_Auth;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.use_id
     *
     * @mbggenerated

     */
    private String use_Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated
     */
    private String user_Password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_auth
     *
     * @mbggenerated
     */
    private String user_Auth;

}